<?php

namespace Database\Seeders;

use App\Models\Location;
use Illuminate\Database\Seeder;

class BangladeshLocationSeeder extends Seeder
{
    public function run(): void
    {
        $locations = [
            // Major Tourist Hotspots
            [
                'name'         => 'Cox\'s Bazar Sea Beach',
                'city'         => 'Cox\'s Bazar',
                'country'      => 'Bangladesh',
                'country_code' => 'BD',
                'latitude'     => 21.4272,
                'longitude'    => 91.9702,
                'is_popular'   => true,
            ],
            [
                'name'         => 'Dhaka City',
                'city'         => 'Dhaka',
                'country'      => 'Bangladesh',
                'country_code' => 'BD',
                'latitude'     => 23.8103,
                'longitude'    => 90.4125,
                'is_popular'   => true,
            ],
            [
                'name'         => 'Sundarbans & Mongla',
                'city'         => 'Sundarbans',
                'country'      => 'Bangladesh',
                'country_code' => 'BD',
                'latitude'     => 22.2858,
                'longitude'    => 89.5852,
                'is_popular'   => true,
            ],
            [
                'name'         => 'Sylhet & Sreemangal',
                'city'         => 'Sylhet',
                'country'      => 'Bangladesh',
                'country_code' => 'BD',
                'latitude'     => 24.8949,
                'longitude'    => 91.8687,
                'is_popular'   => true,
            ],
            [
                'name'         => 'Sajek Valley & Rangamati',
                'city'         => 'Sajek',
                'country'      => 'Bangladesh',
                'country_code' => 'BD',
                'latitude'     => 23.3820,
                'longitude'    => 92.2938,
                'is_popular'   => true,
            ],
            [
                'name'         => 'Kuakata Sunset Beach',
                'city'         => 'Kuakata',
                'country'      => 'Bangladesh',
                'country_code' => 'BD',
                'latitude'     => 21.8166,
                'longitude'    => 90.1198,
                'is_popular'   => true,
            ],
            [
                'name'         => 'Chittagong City',
                'city'         => 'Chittagong',
                'country'      => 'Bangladesh',
                'country_code' => 'BD',
                'latitude'     => 22.3569,
                'longitude'    => 91.7832,
                'is_popular'   => true,
            ],
            [
                'name'         => 'Bandarban Hill District',
                'city'         => 'Bandarban',
                'country'      => 'Bangladesh',
                'country_code' => 'BD',
                'latitude'     => 22.1953,
                'longitude'    => 92.2184,
                'is_popular'   => true,
            ],
            [
                'name'         => 'Saint Martin\'s Island',
                'city'         => 'Saint Martin',
                'country'      => 'Bangladesh',
                'country_code' => 'BD',
                'latitude'     => 20.6273,
                'longitude'    => 92.3225,
                'is_popular'   => true,
            ],
            [
                'name'         => 'Tanguar Haor & Sunamganj',
                'city'         => 'Sunamganj',
                'country'      => 'Bangladesh',
                'country_code' => 'BD',
                'latitude'     => 25.1278,
                'longitude'    => 91.1342,
                'is_popular'   => true,
            ],
            [
                'name'         => 'Khulna City',
                'city'         => 'Khulna',
                'country'      => 'Bangladesh',
                'country_code' => 'BD',
                'latitude'     => 22.8456,
                'longitude'    => 89.5403,
                'is_popular'   => false,
            ],
            [
                'name'         => 'Rajshahi City',
                'city'         => 'Rajshahi',
                'country'      => 'Bangladesh',
                'country_code' => 'BD',
                'latitude'     => 24.3745,
                'longitude'    => 88.6042,
                'is_popular'   => false,
            ],
            [
                'name'         => 'Barisal City',
                'city'         => 'Barisal',
                'country'      => 'Bangladesh',
                'country_code' => 'BD',
                'latitude'     => 22.7010,
                'longitude'    => 90.3535,
                'is_popular'   => false,
            ],
            [
                'name'         => 'Rangpur City',
                'city'         => 'Rangpur',
                'country'      => 'Bangladesh',
                'country_code' => 'BD',
                'latitude'     => 25.7439,
                'longitude'    => 89.2752,
                'is_popular'   => false,
            ],
            [
                'name'         => 'Mymensingh City',
                'city'         => 'Mymensingh',
                'country'      => 'Bangladesh',
                'country_code' => 'BD',
                'latitude'     => 24.7471,
                'longitude'    => 90.4203,
                'is_popular'   => false,
            ],
            [
                'name'         => 'Gazipur & Safari Park',
                'city'         => 'Gazipur',
                'country'      => 'Bangladesh',
                'country_code' => 'BD',
                'latitude'     => 24.0023,
                'longitude'    => 90.4264,
                'is_popular'   => true,
            ],
            [
                'name'         => 'Comilla',
                'city'         => 'Comilla',
                'country'      => 'Bangladesh',
                'country_code' => 'BD',
                'latitude'     => 23.4682,
                'longitude'    => 91.1788,
                'is_popular'   => false,
            ],
            [
                'name'         => 'Bogura',
                'city'         => 'Bogura',
                'country'      => 'Bangladesh',
                'country_code' => 'BD',
                'latitude'     => 24.8465,
                'longitude'    => 89.3777,
                'is_popular'   => false,
            ],
            [
                'name'         => 'Jessore',
                'city'         => 'Jessore',
                'country'      => 'Bangladesh',
                'country_code' => 'BD',
                'latitude'     => 23.1664,
                'longitude'    => 89.2081,
                'is_popular'   => false,
            ],
            [
                'name'         => 'Kushtia',
                'city'         => 'Kushtia',
                'country'      => 'Bangladesh',
                'country_code' => 'BD',
                'latitude'     => 23.9013,
                'longitude'    => 89.1204,
                'is_popular'   => false,
            ],
            [
                'name'         => 'Dinajpur',
                'city'         => 'Dinajpur',
                'country'      => 'Bangladesh',
                'country_code' => 'BD',
                'latitude'     => 25.6279,
                'longitude'    => 88.6332,
                'is_popular'   => false,
            ],
            // International popular destinations
            [
                'name'         => 'Bangkok',
                'city'         => 'Bangkok',
                'country'      => 'Thailand',
                'country_code' => 'TH',
                'latitude'     => 13.7563,
                'longitude'    => 100.5018,
                'is_popular'   => true,
            ],
            [
                'name'         => 'Dubai',
                'city'         => 'Dubai',
                'country'      => 'United Arab Emirates',
                'country_code' => 'AE',
                'latitude'     => 25.2048,
                'longitude'    => 55.2708,
                'is_popular'   => true,
            ],
            [
                'name'         => 'Kuala Lumpur',
                'city'         => 'Kuala Lumpur',
                'country'      => 'Malaysia',
                'country_code' => 'MY',
                'latitude'     => 3.1390,
                'longitude'    => 101.6869,
                'is_popular'   => true,
            ],
            [
                'name'         => 'Singapore',
                'city'         => 'Singapore',
                'country'      => 'Singapore',
                'country_code' => 'SG',
                'latitude'     => 1.3521,
                'longitude'    => 103.8198,
                'is_popular'   => true,
            ],
            [
                'name'         => 'Makkah',
                'city'         => 'Makkah',
                'country'      => 'Saudi Arabia',
                'country_code' => 'SA',
                'latitude'     => 21.3891,
                'longitude'    => 39.8579,
                'is_popular'   => true,
            ],
            [
                'name'         => 'Madinah',
                'city'         => 'Madinah',
                'country'      => 'Saudi Arabia',
                'country_code' => 'SA',
                'latitude'     => 24.5247,
                'longitude'    => 39.5692,
                'is_popular'   => true,
            ],
        ];

        foreach ($locations as $loc) {
            Location::updateOrCreate(
                ['name' => $loc['name']],
                $loc
            );
        }
    }
}
